import type { Metadata } from 'next';

import { Sidebar } from '@/widgets/Sidebar/ui/Sidebar';
import { Container } from '@/shared/ui/Container/Container';

import clsx from 'clsx';

import '@/shared/styles/globals.css';

import { Nunito_Sans } from 'next/font/google';

const nunito = Nunito_Sans({
   subsets: ['latin'],
   variable: '--font-nunito',
   display: 'swap',
   weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
   title: 'Crm rewrite',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={`bg-background-body ${nunito.className} antialiased`}>
            <Container
               className={clsx(
                  'grid min-h-[100vh] w-full grid-cols-12 gap-[1.875rem] p-[1.25rem_2.5rem_1.5625rem_1.25rem]',
               )}
            >
               <Sidebar />
               {children}
            </Container>
         </body>
      </html>
   );
}
