import type { Metadata } from 'next';

import '@/shared/styles/globals.css';
import { Sidebar } from '@/widgets/Sidebar/ui/Sidebar';

export const metadata: Metadata = {
   title: 'Crm rewrite',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={`antialiased`}>
            <Sidebar />
            {children}
         </body>
      </html>
   );
}
