import type { Metadata } from 'next';

import { Sidebar } from '@/widgets/Sidebar/ui/Sidebar';

import '@/shared/styles/globals.css';

import { Nunito_Sans } from 'next/font/google';
import { Header } from '@/widgets/Header/ui/Header';
import { LayoutContainer } from '@/shared/ui/LayoutContainer/LayoutContainer';
import { GlobalWrapper } from '@/shared/ui/GlobalWrapper/GlobalWrapper';

const nunito = Nunito_Sans({
   subsets: ['latin'],
   variable: '--font-nunito',
   display: 'swap',
   weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
   title: 'Crm rewrite',
   description: 'Generated by create next app',
   icons: '/icons/sidebar/sidebar_logo.svg',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={`${nunito.className} antialiased`}>
            <GlobalWrapper>
               <Sidebar />
               <LayoutContainer>
                  <Header />
                  {children}
               </LayoutContainer>
            </GlobalWrapper>
         </body>
      </html>
   );
}
